version: "3.9"

services:
  selenium-hub:
    image: selenium/hub:4.35.0-20250828
    container_name: selenium-hub
    platform: linux/amd64
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    environment:
      - GRID_MAX_SESSION=10
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4444/wd/hub/status" ]
      interval: 5s
      timeout: 3s
      retries: 20

  firefox:
    image: selenium/node-firefox:4.35.0-20250828
    shm_size: 4gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5

  chromium:
    image: selenium/node-chromium:4.35.0-20250828
    shm_size: 4gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5

  chromium_video:
    image: selenium/video:ffmpeg-8.0-20250828
    volumes:
      - /tmp/videos:/videos
    depends_on:
      - chromium
    environment:
      - DISPLAY_CONTAINER_NAME=chromium
      - SE_NODE_GRID_URL=http://selenium-hub:4444
      - SE_VIDEO_FILE_NAME=auto

  firefox_video:
    image: selenium/video:ffmpeg-8.0-20250828
    volumes:
      - /tmp/videos:/videos
    depends_on:
      - firefox
    environment:
      - DISPLAY_CONTAINER_NAME=firefox
      - SE_NODE_GRID_URL=http://selenium-hub:4444
      - SE_VIDEO_FILE_NAME=auto

  file_browser:
    image: filebrowser/filebrowser:latest
    platform: linux/amd64
    container_name: file_browser
    restart: always
    ports:
      - "8081:80"
    volumes:
      - /tmp/videos:/srv
    environment:
      - FB_NOAUTH=true